// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFJwEYUZeSaseeJKVu1tDCdM6PawGqGgk',
    appId: '1:1215704250:web:36453ad278ef4a171f6683',
    messagingSenderId: '1215704250',
    projectId: 'groumap-ea452',
    authDomain: 'groumap-ea452.firebaseapp.com',
    storageBucket: 'groumap-ea452.firebasestorage.app',
    measurementId: 'G-MHF6YHJQKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFJwEYUZeSaseeJKVu1tDCdM6PawGqGgk',
    appId: '1:1215704250:android:f4d72fdc4cabc4181f6683',
    messagingSenderId: '1215704250',
    projectId: 'groumap-ea452',
    storageBucket: 'groumap-ea452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJwEYUZeSaseeJKVu1tDCdM6PawGqGgk',
    appId: '1:1215704250:ios:235272e01951aec61f6683',
    messagingSenderId: '1215704250',
    projectId: 'groumap-ea452',
    storageBucket: 'groumap-ea452.firebasestorage.app',
    iosClientId: '1215704250-235272e01951aec61f6683.apps.googleusercontent.com',
    iosBundleId: 'com.groumap.groumapapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFJwEYUZeSaseeJKVu1tDCdM6PawGqGgk',
    appId: '1:1215704250:ios:235272e01951aec61f6683',
    messagingSenderId: '1215704250',
    projectId: 'groumap-ea452',
    storageBucket: 'groumap-ea452.firebasestorage.app',
    iosClientId: '1215704250-235272e01951aec61f6683.apps.googleusercontent.com',
    iosBundleId: 'com.groumap.groumapapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFJwEYUZeSaseeJKVu1tDCdM6PawGqGgk',
    appId: '1:1215704250:web:36453ad278ef4a171f6683',
    messagingSenderId: '1215704250',
    projectId: 'groumap-ea452',
    authDomain: 'groumap-ea452.firebaseapp.com',
    storageBucket: 'groumap-ea452.firebasestorage.app',
    measurementId: 'G-MHF6YHJQKG',
  );

}
